version: "3.8"
services:
  php:
    build:
      context: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8888:80"
    command: >
      /bin/bash -c '
      composer install && php artisan serve --host=0.0.0.0 --port=80 &
      npm i && npm install vue-loader@^15.9.5 --save-dev --legacy-peer-deps && npm run watch-poll
      '
  mysql:
    image: mysql:8.0
    platform: "linux/amd64"
    environment:
      - TZ=UTC
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
